//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitnessTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseRecord
    {
        public int Id { get; set; }
        public int ExerciseId { get; set; }
        public double RecordTrack { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.DateTime RecordStartDate { get; set; }
        public System.DateTime RecordStartEnd { get; set; }
    
        public virtual Exercise Exercise { get; set; }
    }
}
