//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitnessTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public Exercise()
        {
            this.SetExcercises = new HashSet<SetExcercis>();
            this.ExerciseRecords = new HashSet<ExerciseRecord>();
        }
    
        public int Id { get; set; }
        public string Nane { get; set; }
        public int Target { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<SetExcercis> SetExcercises { get; set; }
        public virtual ICollection<ExerciseRecord> ExerciseRecords { get; set; }
    }
}
