//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitnessTrackerVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public Exercise()
        {
            this.ExerciseRecords = new HashSet<ExerciseRecord>();
            this.Sets = new HashSet<Set>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public double Target { get; set; }
        public string UserID { get; set; }
    
        public virtual ICollection<ExerciseRecord> ExerciseRecords { get; set; }
        public virtual ICollection<Set> Sets { get; set; }
    }
}
