//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitnessTrackerVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseRecord
    {
        public long Id { get; set; }
        public double Record { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long ExerciseId { get; set; }
    
        public virtual Exercise Exercise { get; set; }
    }
}
