//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitnessTrackerWebAPI
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class ExerciseRecordAttribute
    {
        public long Id { get; set; }
        public short AttributeID { get; set; }
        public string Name { get; set; }
        public string Data { get; set; }
        public long ExerciseRecordID { get; set; }

        [JsonIgnore]
        public virtual ExerciseRecord ExerciseRecord { get; set; }
    }
}
