//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
namespace MyFitnessTrackerWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseAttribute
    {
        public long Id { get; set; }
        public short AttributeID { get; set; }
        public string Name { get; set; }
        public string Data { get; set; }
        public long ExerciseId { get; set; }

        [JsonIgnore] 
        public virtual Exercise Exercise { get; set; }
    }
}
